const $=q=>document.querySelector(q),fmt=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
async function login(){let r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("#u").value,password:$("#p").value})});if(!r.ok){alert("Login gagal");return}$("#login").classList.add("hidden");$("#app").classList.remove("hidden");page("dash")}
async function logout(){await fetch("/api/admin/logout",{method:"POST"});location.reload()}
async function api(u,opt){let r=await fetch(u,opt);if(r.status===401){alert("Silakan login kembali");location.reload()}return r.json()}
function page(p){({dash,products,orders,payments,recap}[p])()}
async function dash(){$("#title").textContent="Dashboard";let s=await api("/api/admin/stats");$("#content").innerHTML=`<div class="cards"><div class="stat">🧾<p>Total Pesanan</p><h2>${s.total_orders}</h2></div><div class="stat">🛍️<p>GO Aktif</p><h2>${s.go}</h2></div><div class="stat">💳<p>Menunggu Pembayaran</p><h2>${s.pending}</h2></div><div class="stat">📦<p>Total Ready Stock</p><h2>${s.ready_stock}</h2></div></div><section class="panel"><h2>Pendapatan Terverifikasi</h2><h1 style="color:#e66f9f">${fmt(s.revenue)}</h1></section>`}
async function products(){$("#title").textContent="Produk & GO";let ps=await api("/api/products");$("#content").innerHTML=`<section class="panel"><h2>Tambah Produk / GO</h2><form class="form" onsubmit="addProduct(event)"><select name="type"><option value="go">GO</option><option value="ready">Ready Stock</option></select><input name="name" placeholder="Nama produk" required><input name="price" type="number" placeholder="Harga" required><input name="stock" type="number" placeholder="Stok (Ready Stock)"><input name="deadline" placeholder="Deadline GO"><input name="quota" placeholder="Kuota GO"><input name="options" placeholder="Pilihan: Random,Member" value="Random"><select name="dp_allowed"><option value="0">Tidak ada DP</option><option value="1">DP diizinkan</option></select><button class="btn">Tambah Produk</button></form></section><section class="panel"><h2>Produk Aktif</h2>${ps.map(p=>`<div class="product"><h3>${p.emoji} ${p.name}</h3><p>${p.type} • ${fmt(p.price)} • ${p.type==="go"?p.deadline:"Stok: "+p.stock}</p><div class="actions"><button onclick="archive(${p.id})">Arsipkan</button></div></div>`).join("")}</section>`}
async function addProduct(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.target).entries());d.price=+d.price;d.stock=+d.stock;d.dp_allowed=+d.dp_allowed;await api("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});products()}
async function archive(id){await api("/api/admin/products/"+id,{method:"DELETE"});products()}
async function orders(){$("#title").textContent="Pesanan";let os=await api("/api/admin/orders");$("#content").innerHTML=`<section class="panel"><table><thead><tr><th>Order</th><th>Customer</th><th>Produk</th><th>Total</th><th>Pembayaran</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${os.map(o=>`<tr><td>${o.order_code}</td><td>${o.customer_name}</td><td>${o.items.map(i=>i.product_name+" ×"+i.qty).join("<br>")}</td><td>${fmt(o.total)}</td><td>${o.payment_status}</td><td>${o.order_status}</td><td><button onclick="setStatus(${o.id},'Pesanan Diproses')">Proses</button></td></tr>`).join("")}</tbody></table></section>`}
async function setStatus(id,status){await api("/api/admin/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({order_status:status})});orders()}
async function payments(){
 $("#title").textContent="Pembayaran";let os=await api("/api/admin/orders");
 $("#content").innerHTML=`<section class="panel"><h2>Verifikasi Bukti Pembayaran</h2><table><thead><tr><th>Order</th><th>Customer</th><th>Nominal</th><th>Bukti</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${os.map(o=>`<tr><td>${o.order_code}</td><td>${o.customer_name}</td><td>${fmt(o.amount_due)}</td><td>${o.payment_proof_url?`<a href="${o.payment_proof_url}" target="_blank">Lihat Bukti</a>`:"Belum upload"}</td><td>${o.payment_status}</td><td>${o.payment_proof_url&&o.payment_status!=="Pembayaran Diterima"?`<button class="btn" onclick="verify(${o.id})">Verifikasi</button>`:"-"}</td></tr>`).join("")}</tbody></table></section>`}
async function verify(id){await api("/api/admin/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({payment_status:"Pembayaran Diterima"})});payments()}
async function recap(){$("#title").textContent="Rekap GO";let os=await api("/api/admin/orders"),map={};os.forEach(o=>o.items.forEach(i=>{let k=i.product_name+" — "+i.selected_option;map[k]=(map[k]||0)+i.qty}));$("#content").innerHTML=`<section class="panel"><h2>Rekap Semua Pesanan</h2><table><thead><tr><th>Produk / Pilihan</th><th>Jumlah</th></tr></thead><tbody>${Object.entries(map).map(([k,v])=>`<tr><td>${k}</td><td><b>${v}</b></td></tr>`).join("")}</tbody></table></section>`}